name: Docker Image CI

on:
  push:
    branches: [ "maitri930-patch-1" ]
  pull_request:
    branches: [ "maitri930-patch-1" ]

jobs:

  build:

    runs-on: [ self-hosted ]

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
